-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Aligned_Pulse1.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Aligned_Pulse1
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Aligned Demux/Aligned Pulse1
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Aligned_Pulse1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        earlyPulse                        :   IN    std_logic;
        alignedPulse                      :   OUT   std_logic
        );
END Aligned_Pulse1;


ARCHITECTURE rtl OF Aligned_Pulse1 IS

  -- Signals
  SIGNAL earlyPulse_reg                   : std_logic;
  SIGNAL earlyPulse_reg_next              : std_logic;

BEGIN
  Aligned_Pulse1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      earlyPulse_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        earlyPulse_reg <= earlyPulse_reg_next;
      END IF;
    END IF;
  END PROCESS Aligned_Pulse1_1_process;

  Aligned_Pulse1_1_output : PROCESS (earlyPulse, earlyPulse_reg, valid)
  BEGIN
    earlyPulse_reg_next <= earlyPulse_reg;
    alignedPulse <= (earlyPulse_reg OR earlyPulse) AND valid;
    IF (earlyPulse AND ( NOT valid)) = '1' THEN 
      earlyPulse_reg_next <= '1';
    ELSIF ((earlyPulse_reg OR earlyPulse) AND valid) = '1' THEN 
      earlyPulse_reg_next <= '0';
    END IF;
  END PROCESS Aligned_Pulse1_1_output;


END rtl;

