-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\decoder.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: decoder
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Bank/decoder
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Streaming_2_D_FIR_Filter_pkg.ALL;

ENTITY decoder IS
  PORT( selectWriteLine                   :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        writeValid                        :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(0 TO 1)  -- ufix1 [2]
        );
END decoder;


ARCHITECTURE rtl OF decoder IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL selectWriteLine_unsigned         : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  selectWriteLine_unsigned <= unsigned(selectWriteLine);

  decoder_1_output : PROCESS (selectWriteLine_unsigned, writeValid)
    VARIABLE swl : unsigned(7 DOWNTO 0);
    VARIABLE cast : vector_of_signed32(0 TO 1);
  BEGIN

    FOR i IN 0 TO 1 LOOP
      swl := resize(selectWriteLine_unsigned, 8);
      cast(i) := signed(resize(swl, 32));
      IF (hdlcoder_to_stdlogic(cast(i) = to_signed(i, 32)) AND writeValid) = '1' THEN 
        y(i) <= '1';
      ELSE 
        y(i) <= '0';
      END IF;
    END LOOP;

  END PROCESS decoder_1_output;


END rtl;

