-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Detect_Line_Start.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Line_Start
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Adjust Sync Signals/Detect 
-- Line Star
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Line_Start IS
  PORT( dataValidOut                      :   IN    std_logic;
        colIndex                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        alignedLineStart                  :   OUT   std_logic
        );
END Detect_Line_Start;


ARCHITECTURE rtl OF Detect_Line_Start IS

  -- Signals
  SIGNAL colIndex_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL AND1_out1                        : std_logic;

BEGIN
  colIndex_unsigned <= unsigned(colIndex);

  
  Compare_To_Constant1_out1 <= '1' WHEN colIndex_unsigned = to_unsigned(16#00#, 8) ELSE
      '0';

  AND1_out1 <= dataValidOut AND Compare_To_Constant1_out1;

  alignedLineStart <= AND1_out1;

END rtl;

