-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Detect_Frame_End.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Frame_End
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Adjust Sync Signals/Detect 
-- Frame En
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Frame_End IS
  PORT( lineEnd                           :   IN    std_logic;
        frameHeight                       :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        rowIndex                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        valid                             :   OUT   std_logic
        );
END Detect_Frame_End;


ARCHITECTURE rtl OF Detect_Frame_End IS

  -- Signals
  SIGNAL Constant2_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL frameHeight_unsigned             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rowIndex_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_out1                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL AND1_out1                        : std_logic;

BEGIN
  Constant2_out1 <= to_unsigned(16#01#, 8);

  frameHeight_unsigned <= unsigned(frameHeight);

  rowIndex_unsigned <= unsigned(rowIndex);

  Add_out1 <= resize(Constant2_out1, 9) + resize(rowIndex_unsigned, 9);

  
  Relational_Operator_relop1 <= '1' WHEN frameHeight_unsigned = resize(Add_out1, 16) ELSE
      '0';

  AND1_out1 <= lineEnd AND Relational_Operator_relop1;

  valid <= AND1_out1;

END rtl;

