-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Detect_Valid.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Valid
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Detect Valid
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Valid IS
  PORT( validIn                           :   IN    std_logic;
        initSkipCounter                   :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        repeatLineValid                   :   IN    std_logic;
        initLineCount                     :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        initLinesSkipped                  :   OUT   std_logic;
        valid                             :   OUT   std_logic
        );
END Detect_Valid;


ARCHITECTURE rtl OF Detect_Valid IS

  -- Signals
  SIGNAL initSkipCounter_unsigned         : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL OR2_out1                         : std_logic;

BEGIN
  initSkipCounter_unsigned <= unsigned(initSkipCounter);

  
  Compare_To_Constant1_out1 <= '1' WHEN initSkipCounter_unsigned > to_unsigned(16#1#, 2) ELSE
      '0';

  AND_out1 <= Compare_To_Constant1_out1 AND validIn;

  OR2_out1 <= AND_out1 OR repeatLineValid;

  initLineCount <= initSkipCounter;

  initLinesSkipped <= Compare_To_Constant1_out1;

  valid <= OR2_out1;

END rtl;

