-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Detect_Line_End.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Line_End
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Adjust Sync Signals/Detect 
-- Line En
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Line_End IS
  PORT( dataValidOut                      :   IN    std_logic;
        frameWidth                        :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        colIndex                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        lineEnd                           :   OUT   std_logic
        );
END Detect_Line_End;


ARCHITECTURE rtl OF Detect_Line_End IS

  -- Signals
  SIGNAL Constant2_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL frameWidth_unsigned              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL colIndex_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_out1                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL AND1_out1                        : std_logic;

BEGIN
  Constant2_out1 <= to_unsigned(16#01#, 8);

  frameWidth_unsigned <= unsigned(frameWidth);

  colIndex_unsigned <= unsigned(colIndex);

  Add_out1 <= resize(Constant2_out1, 9) + resize(colIndex_unsigned, 9);

  
  Relational_Operator_relop1 <= '1' WHEN frameWidth_unsigned = resize(Add_out1, 16) ELSE
      '0';

  AND1_out1 <= dataValidOut AND Relational_Operator_relop1;

  lineEnd <= AND1_out1;

END rtl;

