-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\eML_Counter.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: eML_Counter
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Initial Line Skip/eML 
-- Counte
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY eML_Counter IS
  PORT( currentCount                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        enb_1                             :   IN    std_logic;
        reload                            :   IN    std_logic;
        nextCount                         :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
        );
END eML_Counter;


ARCHITECTURE rtl OF eML_Counter IS

  -- Signals
  SIGNAL currentCount_unsigned            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL nextCount_tmp                    : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  currentCount_unsigned <= unsigned(currentCount);

  eML_Counter_1_output : PROCESS (currentCount_unsigned, enb_1, reload)
    VARIABLE add_cast : signed(31 DOWNTO 0);
    VARIABLE add_cast_0 : signed(31 DOWNTO 0);
    VARIABLE add_temp : signed(31 DOWNTO 0);
    VARIABLE cast : unsigned(7 DOWNTO 0);
  BEGIN
    IF reload = '1' THEN 
      nextCount_tmp <= to_unsigned(16#1#, 2);
    ELSIF enb_1 = '1' THEN 
      add_cast := signed(resize(currentCount_unsigned, 32));
      IF (add_cast + 1) <= to_signed(16#00000002#, 32) THEN 
        add_cast_0 := signed(resize(currentCount_unsigned, 32));
        add_temp := add_cast_0 + 1;
        cast := unsigned(add_temp(7 DOWNTO 0));
        IF cast(7 DOWNTO 2) /= "000000" THEN 
          nextCount_tmp <= "11";
        ELSE 
          nextCount_tmp <= cast(1 DOWNTO 0);
        END IF;
      ELSE 
        nextCount_tmp <= currentCount_unsigned;
      END IF;
    ELSE 
      nextCount_tmp <= currentCount_unsigned;
    END IF;
  END PROCESS eML_Counter_1_output;


  nextCount <= std_logic_vector(nextCount_tmp);

END rtl;

