-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Line_Selector.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Line_Selector
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Bank/Line Selector
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Streaming_2_D_FIR_Filter_pkg.ALL;

ENTITY Line_Selector IS
  PORT( selectReadLine                    :   IN    std_logic_vector(0 TO 1);  -- ufix1 [2]
        inputLines                        :   IN    vector_of_std_logic_vector8(0 TO 1);  -- uint8 [2]
        latestPixel                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        y                                 :   OUT   vector_of_std_logic_vector8(0 TO 2)  -- uint8 [3]
        );
END Line_Selector;


ARCHITECTURE rtl OF Line_Selector IS

  -- Signals
  SIGNAL inputLines_unsigned              : vector_of_unsigned8(0 TO 1);  -- uint8 [2]
  SIGNAL latestPixel_unsigned             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL y_tmp                            : vector_of_unsigned8(0 TO 2);  -- uint8 [3]

BEGIN
  outputgen1: FOR k IN 0 TO 1 GENERATE
    inputLines_unsigned(k) <= unsigned(inputLines(k));
  END GENERATE;

  latestPixel_unsigned <= unsigned(latestPixel);

  Line_Selector_1_output : PROCESS (inputLines_unsigned, latestPixel_unsigned, selectReadLine)
    VARIABLE cast : vector_of_signed32(0 TO 1);
  BEGIN

    FOR i IN 0 TO 1 LOOP
      cast(i) := '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & selectReadLine(i);
      y_tmp(i) <= inputLines_unsigned(to_integer(cast(i)));
    END LOOP;

    y_tmp(2) <= latestPixel_unsigned;
  END PROCESS Line_Selector_1_output;


  outputgen: FOR k IN 0 TO 2 GENERATE
    y(k) <= std_logic_vector(y_tmp(k));
  END GENERATE;

END rtl;

