-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Pos_Edge_Detect.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Pos_Edge_Detect
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Read Control/Pos Edge 
-- Detec
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Pos_Edge_Detect IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        x                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END Pos_Edge_Detect;


ARCHITECTURE rtl OF Pos_Edge_Detect IS

  -- Signals
  SIGNAL Unit_Delay1_out1                 : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;

BEGIN
  Unit_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay1_out1 <= x;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_process;


  Logical_Operator2_out1 <=  NOT Unit_Delay1_out1;

  Logical_Operator1_out1 <= x AND Logical_Operator2_out1;

  y <= Logical_Operator1_out1;

END rtl;

