-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\RAM_Blocks.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RAM_Blocks
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Bank/RAM Blocks 
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Streaming_2_D_FIR_Filter_pkg.ALL;

ENTITY RAM_Blocks IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        writeAdd                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        selectWriteRAM                    :   IN    std_logic_vector(0 TO 1);  -- ufix1 [2]
        readAdd                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dataOut                           :   OUT   vector_of_std_logic_vector8(0 TO 1)  -- uint8 [2]
        );
END RAM_Blocks;


ARCHITECTURE rtl OF RAM_Blocks IS

  -- Component Declarations
  COMPONENT Dynamic_RAM_Blocks
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          writeAdd                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          selectWriteRAM                  :   IN    std_logic_vector(0 TO 1);  -- ufix1 [2]
          readAdd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          dataOut                         :   OUT   vector_of_std_logic_vector8(0 TO 1)  -- uint8 [2]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Dynamic_RAM_Blocks
    USE ENTITY work.Dynamic_RAM_Blocks(rtl);

  -- Signals
  SIGNAL Dynamic_RAM_Blocks_out1          : vector_of_std_logic_vector8(0 TO 1);  -- ufix8 [2]

BEGIN
  u_Dynamic_RAM_Blocks : Dynamic_RAM_Blocks
    PORT MAP( clk => clk,
              enb => enb,
              dataIn => dataIn,  -- uint8
              writeAdd => writeAdd,  -- uint8
              selectWriteRAM => selectWriteRAM,  -- ufix1 [2]
              readAdd => readAdd,  -- uint8
              dataOut => Dynamic_RAM_Blocks_out1  -- uint8 [2]
              );

  dataOut <= Dynamic_RAM_Blocks_out1;

END rtl;

