-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Select_All_Output_Rows.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Select_All_Output_Rows
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Line Memory Controller/Select All Output 
-- Row
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Streaming_2_D_FIR_Filter_pkg.ALL;

ENTITY Select_All_Output_Rows IS
  PORT( readLineCount                     :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        y                                 :   OUT   std_logic_vector(0 TO 1)  -- ufix1 [2]
        );
END Select_All_Output_Rows;


ARCHITECTURE rtl OF Select_All_Output_Rows IS

  -- Signals
  SIGNAL readLineCount_unsigned           : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  readLineCount_unsigned <= unsigned(readLineCount);

  Select_All_Output_Rows_1_output : PROCESS (readLineCount_unsigned)
    VARIABLE lut_vec : std_logic_vector(0 TO 3);
    VARIABLE j : signed(31 DOWNTO 0);
    VARIABLE lut_r : unsigned(7 DOWNTO 0);
    VARIABLE fx_lut_ele : std_logic;
    VARIABLE out_rsvd : std_logic_vector(0 TO 1);
    VARIABLE add_cast : signed(31 DOWNTO 0);
    VARIABLE add_temp : signed(31 DOWNTO 0);
    VARIABLE add_cast_0 : vector_of_signed32(0 TO 1);
    VARIABLE add_cast_1 : vector_of_signed64(0 TO 1);
    VARIABLE j_0 : vector_of_signed33(0 TO 1);
    VARIABLE sub_cast : vector_of_signed32(0 TO 1);
    VARIABLE sub_temp : vector_of_signed32(0 TO 1);
    VARIABLE sub_cast_0 : vector_of_signed8(0 TO 1);
    VARIABLE sub_temp_0 : vector_of_signed8(0 TO 1);
    VARIABLE add_cast_2 : vector_of_signed64(0 TO 1);
  BEGIN
    -- output word-length
    add_cast := signed(resize(readLineCount_unsigned, 32));
    add_temp := add_cast + 1;
    lut_r := unsigned(add_temp(7 DOWNTO 0));

    FOR k IN 0 TO 1 LOOP

      FOR i IN 0 TO 1 LOOP
        j := (to_signed(i - 3, 32) + to_signed(k, 32)) + 1;
        IF j < to_signed(16#00000000#, 32) THEN 
          j_0(i) :=  - (resize(j, 33));
          sub_cast(i) := j_0(i)(31 DOWNTO 0);
          sub_temp(i) := sub_cast(i) - 1;
          sub_cast_0(i) := sub_temp(i)(7 DOWNTO 0);
          sub_temp_0(i) := 1 - sub_cast_0(i);
          out_rsvd(i) := sub_temp_0(i)(0);
        ELSE 
          out_rsvd(i) := '0';
        END IF;
        add_cast_2(i) := resize(to_signed(k, 32) & '0', 64);
        lut_vec(to_integer(to_signed(i, 32) + resize(add_cast_2(i), 32))) := out_rsvd(i);
      END LOOP;

      add_cast_0(k) := signed(resize(lut_r, 32));
      add_cast_1(k) := resize(to_signed(k, 32) & '0', 64);
      fx_lut_ele := lut_vec(to_integer((add_cast_0(k) + resize(add_cast_1(k), 32)) - 1));
      y(k) <= fx_lut_ele;
    END LOOP;

  END PROCESS Select_All_Output_Rows_1_output;


END rtl;

