vlib work
vcom  Streaming_2_D_FIR_Filter_pkg.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  Delay_balance.vhd
vcom  Sync_Demux.vhd
vcom  Aligned_Pulse.vhd
vcom  Aligned_Pulse1.vhd
vcom  Aligned_Demux.vhd
vcom  Dynamic_RAM_Blocks.vhd
vcom  RAM_Blocks.vhd
vcom  Line_Selector.vhd
vcom  decoder.vhd
vcom  Line_Memory_Bank.vhd
vcom  Detect_Frame_End.vhd
vcom  Detect_Frame_Start.vhd
vcom  Detect_Line_End.vhd
vcom  Detect_Line_Start.vhd
vcom  SyncMux.vhd
vcom  Adjust_Sync_Signals.vhd
vcom  Detect_Valid.vhd
vcom  eML_Counter.vhd
vcom  Initial_Line_Skip.vhd
vcom  eML_Counter_block.vhd
vcom  Out_Row_Count.vhd
vcom  eML_Counter_block1.vhd
vcom  Read_Col_Counter.vhd
vcom  eML_Counter_block2.vhd
vcom  Hold_Valid_Counter.vhd
vcom  Pos_Edge_Detect.vhd
vcom  Pos_Edge_Detect1.vhd
vcom  eML_Counter_block3.vhd
vcom  Repeat_Counter.vhd
vcom  Time_Distance.vhd
vcom  Time_Distance_block.vhd
vcom  Aligned_to_Second_Pulse.vhd
vcom  Bit_Set.vhd
vcom  Read_Control.vhd
vcom  eML_Counter_block4.vhd
vcom  Read_Line_Counter1.vhd
vcom  Read_Line_Count.vhd
vcom  eML_Counter_block5.vhd
vcom  Write_Col_Counter.vhd
vcom  eML_Counter_block6.vhd
vcom  Write_Line_Counter.vhd
vcom  Select_All_Output_Rows.vhd
vcom  Line_Memory_Controller.vhd
vcom  Line_Memory.vhd
vcom  Make_Neighborhood.vhd
vcom  Make_Neighborhood_block.vhd
vcom  Streaming_2_D_FIR_Filter.vhd
