-- -------------------------------------------------------------
-- 
-- File Name: Streaming_VHDL\fil_videosharp_sim\Sync_Demux.vhd
-- Created: 2019-06-18 09:45:08
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sync_Demux
-- Source Path: fil_videosharp_sim/Streaming 2-D FIR Filter/Line Memory/Aligned Demux/Sync Demux
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sync_Demux IS
  PORT( syncSignals                       :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        activePixel                       :   OUT   std_logic;
        lineStart                         :   OUT   std_logic;
        frameStart                        :   OUT   std_logic;
        frameEnd                          :   OUT   std_logic
        );
END Sync_Demux;


ARCHITECTURE rtl OF Sync_Demux IS

  -- Signals
  SIGNAL syncSignals_unsigned             : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL dtc1                             : std_logic;  -- ufix1
  SIGNAL Extract_Bits_out1                : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion_out1        : std_logic;
  SIGNAL dtc1_1                           : std_logic;  -- ufix1_E1
  SIGNAL Extract_Bits1_out1               : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1       : std_logic;
  SIGNAL dtc1_2                           : std_logic;  -- ufix1_E3
  SIGNAL Extract_Bits3_out1               : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion3_out1       : std_logic;
  SIGNAL Extract_Bits4_out1               : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion4_out1       : std_logic;

BEGIN
  syncSignals_unsigned <= unsigned(syncSignals);

  dtc1 <= syncSignals_unsigned(0);

  Extract_Bits_out1 <= dtc1;

  
  Data_Type_Conversion_out1 <= '1' WHEN Extract_Bits_out1 /= '0' ELSE
      '0';

  dtc1_1 <= syncSignals_unsigned(1);

  Extract_Bits1_out1 <= dtc1_1;

  
  Data_Type_Conversion1_out1 <= '1' WHEN Extract_Bits1_out1 /= '0' ELSE
      '0';

  dtc1_2 <= syncSignals_unsigned(3);

  Extract_Bits3_out1 <= dtc1_2;

  
  Data_Type_Conversion3_out1 <= '1' WHEN Extract_Bits3_out1 /= '0' ELSE
      '0';

  Extract_Bits4_out1 <= syncSignals_unsigned(4);

  
  Data_Type_Conversion4_out1 <= '1' WHEN Extract_Bits4_out1 /= '0' ELSE
      '0';

  activePixel <= Data_Type_Conversion_out1;

  lineStart <= Data_Type_Conversion1_out1;

  frameStart <= Data_Type_Conversion3_out1;

  frameEnd <= Data_Type_Conversion4_out1;

END rtl;

