
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'adau1761_test.ucf'
####################################################################################

###########################################
# XDC file for the Zedboard+ADAU1761 codec
#
# converted from ISE 14.4 to Vivado 2014.2
###########################################
#

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:6
create_clock -period 10.000 -name clk_100 [get_ports clk_100]
set_property PACKAGE_PIN Y9 [get_ports clk_100]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:6
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk_100' has been applied to the port object 'clk_100'.
set_property IOSTANDARD LVCMOS33 [get_ports clk_100]

set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:8
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_ADR0' has been applied to the port object 'AC_ADR0'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:9
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_ADR1' has been applied to the port object 'AC_ADR1'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR1]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:10
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_GPIO0' has been applied to the port object 'AC_GPIO0'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_GPIO1' has been applied to the port object 'AC_GPIO1'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO1]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:12
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_GPIO2' has been applied to the port object 'AC_GPIO2'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO2]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_GPIO3' has been applied to the port object 'AC_GPIO3'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO3]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:14
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_SCK' has been applied to the port object 'AC_SCK'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_SCK]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_SDA' has been applied to the port object 'AC_SDA'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_SDA]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:16
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AC_MCLK' has been applied to the port object 'AC_MCLK'.
set_property IOSTANDARD LVCMOS33 [get_ports AC_MCLK]

# "SW0"
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:18
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[0]' has been applied to the port object 'sw[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]
# "SW1"
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[1]' has been applied to the port object 'sw[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
# "SW2"
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:20
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[2]' has been applied to the port object 'sw[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
# "SW3"
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:21
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[3]' has been applied to the port object 'sw[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
# "SW4"
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:22
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[4]' has been applied to the port object 'sw[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[4]}]
# "SW5"
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[5]' has been applied to the port object 'sw[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[5]}]
# "SW6"
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:24
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[6]' has been applied to the port object 'sw[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[6]}]
# "SW7"
set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
# D:/student_Assis/Feb_2015/dsp_base_project/adau1761_test.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw[7]' has been applied to the port object 'sw[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {sw[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN Y11 [get_ports {seg[0]}]
set_property PACKAGE_PIN AA11 [get_ports {seg[1]}]
set_property PACKAGE_PIN Y10 [get_ports {seg[2]}]
set_property PACKAGE_PIN AA9 [get_ports {seg[3]}]
set_property PACKAGE_PIN W12 [get_ports {seg[4]}]
set_property PACKAGE_PIN W11 [get_ports {seg[5]}]
set_property PACKAGE_PIN V10 [get_ports {seg[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports segsel]
set_property PACKAGE_PIN U14 [get_ports segsel]
