# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/rbhar/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-23680-DESKTOP-MNL47F2/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -ruleid {2147483647}  -id {Board 49-4}  -new_severity {WARNING} 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.cache/wt [current_project]
set_property parent.project_path D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/i3c2.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/adau1761_configuraiton_data.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/i2s_data_interface.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/i2c.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/ADAU1761_interface.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/low_pass_moving_sum.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/dsp_block.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/clocking.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/adau1761_izedboard.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/sources_1/imports/audio24bit_7Seg/adau1761_test.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/constrs_1/imports/ss2015/dsp_prj_migrated.xdc
set_property used_in_implementation false [get_files D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab1/audio24bit_Vivado_2018_2/audio24bit/audio24bit.srcs/constrs_1/imports/ss2015/dsp_prj_migrated.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top adau1761_test -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adau1761_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file adau1761_test_utilization_synth.rpt -pb adau1761_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
