# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.cache/wt [current_project]
set_property parent.project_path D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/jtag_mac.v
read_vhdl -library xil_defaultlib {
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Detect_Line_Start.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Detect_Line_End.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Detect_Frame_Start.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Detect_Frame_End.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/SyncMux.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Adjust_Sync_Signals.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Sync_Demux.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Aligned_Pulse.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Aligned_Pulse1.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Aligned_Demux.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Aligned_to_Second_Pulse.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Bit_Set.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/SimpleDualPortRAM_generic.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Delay_balance.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Detect_Valid.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Streaming_2_D_FIR_Filter_pkg.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Dynamic_RAM_Blocks.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block2.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Hold_Valid_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Initial_Line_Skip.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block5.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Write_Col_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block6.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Write_Line_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block3.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Repeat_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Time_Distance.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Time_Distance_block.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Pos_Edge_Detect.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Pos_Edge_Detect1.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Read_Control.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block1.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Read_Col_Counter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block4.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Read_Line_Counter1.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Read_Line_Count.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Select_All_Output_Rows.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/eML_Counter_block.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Out_Row_Count.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Line_Memory_Controller.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/decoder.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/RAM_Blocks.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Line_Selector.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Line_Memory_Bank.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Line_Memory.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Make_Neighborhood.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Make_Neighborhood_block.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_VHDL/fil_videosharp_sim/Streaming_2_D_FIR_Filter.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/Streaming_2_D_FIR_Filter_wrapper.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/jtag_mac_fifo_wrapper.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_bus2dut.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_chifcore.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_chiftop.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_controller.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_dpscram.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_dut2bus.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/mwfil_udfifo.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/simcycle_fifo_wrapper.vhd
  D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/Streaming_2_D_FIR_Filter_fil.vhd
}
read_ip -quiet d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc]

read_ip -quiet d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/fpgaproj/Streaming_2_D_FIR_Filter_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/Streaming_2_D_FIR_Filter_fil.xdc
set_property used_in_implementation false [get_files D:/HDA/2_sem/DesignAndTestOfMicroelectronics/Lab/Lab3/Streaming_2_D_FIR_Filter_fil/filsrc/Streaming_2_D_FIR_Filter_fil.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Streaming_2_D_FIR_Filter_fil -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Streaming_2_D_FIR_Filter_fil.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Streaming_2_D_FIR_Filter_fil_utilization_synth.rpt -pb Streaming_2_D_FIR_Filter_fil_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
